version: "3.9"
   
services:
  server:
    image: myserver:1.0
    build: ./server
    command: bash ./server.sh
    volumes:
      - type: bind
        source: $PWD/server/nginx/
        target: /etc/nginx/conf.d/
    ports:
      - "8080:81"
  nginx:
    image: mynginx:1.0
    build: ./client
    command: bash ./server.sh
    ports:
      - "80:8080"

